# 数据库配置
databases:
  dbAppA:
    host: 18.163.217.121
    port: "3306"
    user: zhixietong
    password: "jSdTS3fWyC8XLeNK"
    name: zhixietong

  dbAppB:
    host: 18.163.217.121
    port: "3306"
    user: simpleim
    password: "4LLsjhLDLMtnpkCW"
    name: simpleim


